In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
x = torch.arange(4)
x,x[3]

(tensor([0, 1, 2, 3]), tensor(3))

In [4]:
len(x)

4

In [5]:
x.shape

torch.Size([4])

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
X = torch.arange(24).reshape(2, 3, 4)
X.T.T

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [11]:
A,B,A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

降维,对每一行或列直接sum会对其降维,并默认为下一维的表示方式,采用sum（,keepdims=True）不会降维

In [ ]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

In [ ]:
A_sum_axis0 = A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape

In [ ]:
A.sum(axis=[0, 1]),A.sum()  # Same as `A.sum()`

In [ ]:
A.numel(),A.shape,A.sum()/A.numel(),A.mean()

In [ ]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]#对每行求平均

In [ ]:
sum_A = A.sum(axis=1, keepdims=True)#保持轴不动的降维
sum_A,A.sum(axis=0,keepdims=True),A.sum(axis=1),A.sum()

例如，由于 sum_A 在对每行进行求和后仍保持两个轴，我们可以通过广播将 A 除以 sum_A 。

In [ ]:
A / sum_A,A / A.sum()#前者为每行归一化，后者是整个张量归一化

如果我们想沿某个轴计算 A 元素的累积总和，比如 axis=0（按行计算），我们可以调用 cumsum 函数。此函数不会沿任何轴降低输入张量的维度。

In [ ]:
A,A.cumsum(axis=0)#按行方向累计求和

点积,当我们为矩阵 A 和向量 x 调用 np.dot(A, x)时，会执行矩阵-向量积。注意，A 的列维数（沿轴1的长度）必须与 x 的维数（其长度）相同。

In [ ]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y),torch.sum(x * y)

In [ ]:
A,x,A.shape, x.shape, torch.mv(A, x)

In [ ]:
B = torch.ones(4, 3)
torch.mm(A, B)

可以按如下方式计算向量的  L2  范数和L1范数。

In [ ]:
u = torch.tensor([3.0, -4.0])
torch.norm(u),torch.abs(u).sum()

In [ ]:
torch.norm(torch.ones((4, 9)))#矩阵的二阶范数，元素平方和开根号

In [ ]:
K=torch.arange(24).reshape(2,3,4)
K,len(K),K.size()

In [ ]:
K.sum(axis=0,keepdims=True)

In [ ]:
K.sum(axis=1,keepdims=True),K.sum(axis=2,keepdims=True)